import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "../globals.css";
import Header from "@/components/Header";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { Toaster } from "@/components/ui/sonner";

const font = Cairo({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Optimizer",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale} dir={locale == "ar" ? "rtl" : "ltr"}>
      <body
        dir={locale == "ar" ? "rtl" : "ltr"}
        className={`${font.className} antialiased `}>
        <NextIntlClientProvider>
          <Header />
          {children}
          <Toaster
            closeButton={true}
            position={locale == "ar" ? "bottom-left" : "bottom-right"}
            richColors
            theme="light"
          />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
